### ISSUE TITLE
Simplify navigator.globalPrivacyControl wording

### ISSUE THREAD

**Issue by scottlow** [globalprivacycontrol/gpc-spec#11]
The spec text currently reads as follows:

> Specifically, the value of Navigator.globalPrivacyControl for a given script is true if a Sec-GPC header set to 1 is sent in a request to a target resource at the effective script origin (the current document.domain of the script's responsible document) when that request is due to an embedded reference from this site (the document.domain of the top-level browsing context's active document). Otherwise, it is false.

It seems that this was a direct copy and paste from [DNT](https://w3c.github.io/dnt/drafts/purposes-snapshot.html#js-dom). I believe that the wording about when the JS attribute should return `true` versus `false` was necessary under DNT due to the idea of [user-granted exceptions](https://w3c.github.io/dnt/drafts/purposes-snapshot.html#exceptions). Given that there is no such notion under GPC (since it is a global control), it seems there's an opportunity to simplify this language:

> Specifically, the value of Navigator.globalPrivacyControl for a given script is true if a user has requested that their data "not be sold or shared" via setting a Global Privacy Control preference.

Happy to submit a PR if folks agree to the wording above!

**Comment by dharb** [comment]
Thanks @scottlow, I like the simplification. The only concern I have is I think some implementers may have linked the injection of the signal to tracking protection being turned on, so when a user "safelists" (manually disables protection for) a domain, the signal isn't injected there. For instance, https://github.com/EFForg/privacybadger/pull/2693.

@darobin what do you think? Do we need to explicitly call out that the DOM signal directly reflects the header signal here?

**Comment by ghostwords** [comment]
Hi everyone,

Here is a downside of setting `navigator.globalPrivacyControl` to `false` when the signal is disabled: https://github.com/EFForg/privacybadger/issues/2717

A user with Privacy Badger (GPC on by default) and DuckDuckGo Privacy Essentials (GPC off by default) reported GPC not working. What happened is Privacy Badger's content script sets `navigator.globalPrivacyControl` to `true` (in page JS contexts), but DDG then comes in and overwrites `navigator.globalPrivacyControl` to `false`.

This is the second time already Privacy Badger received a bug report with this behavior.

I'm not completely clear on whether this is a problem with the spec or with the DDG extension. Apologies if this isn't in the right place. Just raising an issue we noticed over at Privacy Badger.

**Comment by dharb** [comment]
Hey @ghostwords, thanks for reporting this behavior. I just took a look and I think I see what's happening here.

Privacy Badger is setting the `navigator.globalPrivacyControl` property with the following [code](https://github.com/EFForg/privacybadger/blob/master/src/js/contentscripts/dnt.js#L31-L35):
``` JavaScript
OBJECT.defineProperty(OBJECT.getPrototypeOf(NAVIGATOR), "globalPrivacyControl", {
  get: function globalPrivacyControl() {
    return "1";
  }
});
```
Then DuckDuckGo Privacy Essentials is setting the `navigator.globalPrivacyControl` property with the following [code](https://github.com/duckduckgo/duckduckgo-privacy-extension/blob/develop/shared/js/content-scripts/GPC.js#L21-L28), which is overriding the value set by Privacy Badger:
``` JavaScript
try {
  Object.defineProperty(navigator, 'globalPrivacyControl', {
    value: false
  })
} catch(e) {}
```
I put the `try...catch` block there in anticipation of other extensions having already set the value directly, which would make this throw an error (attempts to redefine a value defined this way will throw errors since it is by default non-configurable).

So basically what's happening here is we're using two different ways (defining the getter and defining the property value) to set the `navigator.globalPrivacyControl` value, and one is overriding the other. I think there are two potential solutions here:

1. Set both the getter and the value, and wrap in a `try...catch` block. This would throw an error when the value has already been set via either method, which would prevent overriding a signal that's already been set by another extension:
``` JavaScript
try {
  // will throw error if getter has already been defined
  Object.defineProperty(navigator, 'globalPrivacyControl', {
    get: function globalPrivacyControl() {
      return true;
    }
  })
  // will throw error if value has already been defined
  Object.defineProperty(navigator, 'globalPrivacyControl', {
    value: true,
  })
} catch(e) {}
```
2. Privacy Badger defines value directly instead of defining the getter.

I'd be happy to make change #1 in the DDG extension to ensure better compat with other extensions, but first out of curiosity is there any reason why Privacy Badger is defining the getter instead of the value itself?

**Comment by ghostwords** [comment]
I see, [data descriptors vs. accessor descriptors](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty). I suppose we use a getter because it's more flexible, but there is no particular need to use it at this point. We haven't run into cross-extension issues up until now.

**Comment by ghostwords** [comment]
If a user has multiple GPC-capable extensions installed, but only one extension has GPC enabled, should the GPC signal be sent? If the answer is yes, then:

- We should make sure to overwrite GPC in navigator in the most robust way when GPC is enabled, to handle cases when an extension that sets GPC to `false` was injected first. It sounds like this may not be possible depending on exactly how that extension set GPC to `false`.
- Extensions that set GPC to `false` when GPC is disabled should take care to not overwrite GPC in navigator when a GPC-on extension's content script was injected first.

We wouldn't have this complexity if extensions didn't inject anything when GPC is disabled.

**Comment by ghostwords** [comment]
@dharb By the way, we have a similar problem with `navigator.doNotTrack` where DDG overwrites the user's preference, whether set via Privacy Badger or the browser's own DNT toggle.

**Comment by dharb** [comment]
>If a user has multiple GPC-capable extensions installed, but only one extension has GPC enabled, should the GPC signal be sent?

Yes, definitely. If a user has any tool installed that has GPC on, the GPC signal should be sent.

I agree 100% with your logic here. Extensions should set GPC to `true` using the most robust method possible, and should set GPC to `false` in a way that can be overridden by another extension that has GPC on. With this in mind, what do you think about the following extension implementation guidelines?

#### GPC off:
First check if `navigator.globalPrivacyControl` is defined and set to `true`. If yes, then do nothing. Otherwise set `navigator.globalPrivacyControl` to `false` on the prototype as follows:
```` JavaScript
if (navigator.globalPrivacyControl) return
Object.defineProperty(Object.getPrototypeOf(navigator), 'globalPrivacyControl', {
    value: false
})
````

#### GPC on:
First check if `navigator.globalPrivacyControl` is defined and set to `true`. If yes, then do nothing. Otherwise set `navigator.globalPrivacyControl` to `true` as follows:
```` JavaScript
if (navigator.globalPrivacyControl) return
Object.defineProperty(navigator, 'globalPrivacyControl', {
    value: true
})
````

Then if a user has two conflicting extensions that support GPC, say Extension1 and Extension2, and Extension1 is installed first:
#### Extension1 has GPC on, Extension2 has GPC off
- Since Extension2 was installed most recently, it will first set `globalPrivacyControl` to `false` on the navigator prototype
- Then Extension1 will set `navigator.globalPrivacyControl` to `true`, which will override the prototype property. So `navigator.globalPrivacyControl` will return `true`
#### Extension1 has GPC off, Extension2 has GPC on
- Since Extension2 was installed most recently, it will first set `navigator.globalPrivacyControl` to `true`
- Extension1 will see that `navigator.globalPrivacyControl` is truthy and not do anything

@ghostwords if this approach or something similar works for you, maybe we could align and do something similar with other navigator properties we're setting via our extensions.

**Comment by ghostwords** [comment]
Sounds good! Please take a look at https://github.com/EFForg/privacybadger/pull/2722

**Comment by darobin** [comment]
I've taken @scottlow's change, which is definitely an improvement. I believe that the extension-related issues have been addressed separately — let me know if that's a problem!

**Comment by eligrey** [comment]
Reading these comments, it seems like there is some confusion regarding the spec and how JavaScript accessors work.

Trying to define a non-configurable accessor twice will throw an error. As I understand it (and as it has been implemented in Brave), this accessor should be configurable to user JS.

My consent manager expects all implementations to work as such, since the IDL in the spec says that this is implemented on `Navigator` and not directly on `navigator`:

```ts
if (!Navigator.prototype.hasOwnProperty('globalPrivacyControl')) {
  Object.defineProperty(Navigator.prototype, 'globalPrivacyControl', {
    get: () => true, // or whatever the user has configured for GPC
    configurable: true // prevents errors when other scripts attempt to redefine this property
    enumerable: true
  });
}
```

**Comment by dharb** [comment]
Thanks @eligrey, appreciate the feedback. I'm open to making this change in DDG's implementations, but would love to hear others' thoughts here as well. For background, there were two primary reasons we went with the current implementation:

### Conflicts caused by competing defaults
Not all implementations set GPC on by default. This can lead to two types of conflicts:
1. User's browser or previously installed extension sets GPC on by default, then user unknowingly turns GPC off by installing an extension that implements GPC but doesn't turn it on by default. Ideally if a user's browser or any installed extension is setting GPC on, it shouldn't be overridden by another extension that is setting GPC off by default.
2. User's browser or previously installed extension implements GPC but does not turn it on by default, then user installs extension that sets GPC on by default. This is only an issue if the extension first checks `if (!Navigator.prototype.hasOwnProperty('globalPrivacyControl'))` before setting the GPC DOM signal, since `Navigator.prototype.globalPrivacyControl` will already be defined as `false` here. Less concerned about this case, we can make it work.

### Preventing scripts from tampering with GPC signal
If we allow the GPC DOM property to be configurable, it's possible for a malicious script (or website even) to change the value and prevent the signal from propagating correctly. That is to say, if a website checks `navigator.globalPrivacyControl` before each third party script is loaded, it's possible that this value may not reflect the user's preference. I like your suggestion in the other thread to use `Object.getOwnPropertyDescriptor(Navigator.prototype, 'globalPrivacyControl')?.get.call(navigator)`, but I'm not sure we can count on websites to check the value this way instead of just checking `navigator.globalPrivacyControl`. Either way, I think this is probably a pretty rare edge case and not such a big deal.

**Comment by eligrey** [comment]
> ## Conflicts caused by competing defaults

> Ideally if a user's browser or any installed extension is setting GPC on, it shouldn't be overridden by another extension that is setting GPC off by default.

IMO users should be free to install extensions with conflicting behaviors. It's on implementors to try to coexist with each other. I'd prefer if extension-based and web-based implementations backed off if GPC is natively supported by the browser. If this signal is natively supported by the browser, then the browser vendor should provide a settings API which allows extension authors to modify this value.

> ## Preventing scripts from tampering with GPC signal

If a script wants to tamper with GPC, I feel like that's fine. It should be up to the site owner and/or user as to what happens with this property. For example, a site owner or user's user agent (Browser or extension) may want to polyfill or modify this feature.

If tamper prevention is an intended design goal for this API, you should add `[Unforgeable]` to the WebIDL in the spec. This should not affect API consumers.

Also, some clarification with `Object.getOwnPropertyDescriptor(Navigator.prototype, 'globalPrivacyControl')?.get.call(navigator)`: This doesn't actually make `navigator.globalPrivacyControl` references secure by itself. I cache interfaces that I may need to use post-init due to potentially hostile code trying to backdoor my post-init environment.

For example, I could securely resolve `navigator.globalPrivacyControl` post-init if I so wished, by building on top of references that I know are secure due to the a script being the first to load:

```
// assume potential prototype pollution post-init
// assume all uninitialized variables in this example are cached references
if (navigator && gpcGetter) {
  const GPC = call(gpcGetter, navigator);
  if (GPC) {
    // do something with GPC
  }
} 
```

We just want to plug GPC into our secure reference system without having to special-case for different implementations.
