### ISSUE TITLE
Standardized server-side response when GPC compliance cannot be guaranteed

### ISSUE THREAD

**Issue by KoopaKing** [globalprivacycontrol/gpc-spec#29]
Random question, but when looking through the spec I didn't see anything about what responses should be for rejecting requests which cannot be satisfied while respecting GPC headers.

I'm very new to this space, so maybe this question is stupid, but it seems like there would be some times where a server cannot guarantee that they are compliant with legal requirements of a request specifying `Sec-GPC: 1`. In those situations it may make sense to reject the request entirely, or indicate this information to clients in a standardized way. Is there any guidance about what a server responses (and response codes) should look like for that type of situation?

**Comment by AramZS** [comment]
Hi @KoopaKing 

I'm not entirely clear on what you are requesting. If this is a question about a response to the on-page `navigator` Javascript object that GPC is providing, that API does not respond and you should not send messages to it. Generally [the way you say your site is listening for GPC is to have the `.well-known` resource](https://globalprivacycontrol.github.io/gpc-spec/#gpc-support-representation). 

If you are asking about a HTTP response on the basis of the request coming in with a GPC header, the spec does not suggest a specific response or response code. I'd suspect that your response will change on the basis of why you are rejecting the request. The 451, 403, 412 [and more error codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) might be appropriate depending on both the reason and style of the rejection. That said, some laws have specific language around not forbidding users access on the basis of a privacy choice and you should consult with a lawyer before choosing to reject a request because it has a privacy preference attached. 

Does that answer your question @KoopaKing ?

**Comment by KoopaKing** [comment]
@AramZS yes that does answer my question. I was really asking about the latter, for requests coming into an API server that happen to specify this, it seems like if the API implementor was not sure of the legal requirements associated with handling a specific request, they may opt for not processing and instead returning an appropriate error.

I agree that depending on the exact reason for thinking the request cannot be processed different error codes may be correct, but I had originally thought that there may be some use in a standardized code or response type for this situation.

My use case was mostly just exploritory. Specifically I have some REST APIs and that use gRPC+Go on the backend and was adding a request processor to easily access the GPC indicator on the request, and make canned decisions before handing the request off to the business logic layer. As a library it seemed like one way you would want to configure it would be to deny requests with that indicator that also meet some condition (maybe a source IP range believed to be in an unsupportable location). I thought I'd ask if the project itself had a recommendation for standardized "I can't process this in a guaranteed GPC-compatible way" response. If not, all good.

Thanks for the response!
