### ISSUE TITLE
Describe caching expectations for /.well-known/gpc

### ISSUE THREAD

**Issue by asoltani** [globalprivacycontrol/gpc-spec#3]

**Comment by mnot** [comment]
What did you have in mind here? It should cache just like any other HTTP response...

**Comment by darobin** [comment]
This is here because DNT [does specify caching](https://www.w3.org/TR/tracking-dnt/#status-caching) and I wanted to be sure that I was not overlooking some reason to have specific caching rules. I think that the model we landed on for GPC means we don't need to care, but I wanted to check my assumptions.

**Comment by darobin** [comment]
Having reviewed this more closely, I don't think we need to say anything specific.
